name: run jupyter notebook

on: 
  push:
    # branches:
    #   - master    
  schedule:
    - cron: 0 4,7,10,13,16,20 * * *

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r notebook/requirements.txt        
    - uses: yaananth/run-notebook@v1
      env:
        RUNNER: ${{ toJson(runner) }}
        #SECRETS: ${{ toJson(secrets) }}
        SECRETS: "${{ format('{{ \"webcom_key\" : \"{0}\" }}', secrets.WEBCOM_KEY) }}"
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "notebook/AirQuality.ipynb"
        params: "notebook/airquality-config.json"
        isReport: False
        poll: True
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: output
        path: ${{ RUNNER.temp }}/nb-runner
      env:
        RUNNER: ${{ toJson(runner) }}
    - name: publish to pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: output
        keep_history: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
